remote_theme: "jekyll/minima@1e8a445"

title: IBEX Imaging Community

header_pages:
  - index.md
  - reagent_resources.md
  - protocols.md
  - videos.md
  - data_and_software.md
  - publications.md
  - q_and_a.md
  - contrib.md
  - leadership.md

minima:
  skin: classic

plugins:
  - jekyll-titles-from-headings
  - jekyll-relative-links

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

