name: Create Draft Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    runs-on: macos-latest
    env:
      RELEASE_NOTES_FILE: release_notes.md
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Create draft notes
        shell: bash
        run: |
          pip install --upgrade pip
          pip install https://github.com/IBEXImagingCommunity/ibex_imaging_knowledge_base_utilities/releases/download/v0.9.8/ibex_imaging_knowledge_base_utilities-0.9.8-py3-none-any.whl
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ github.ref_name }}^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "We are proud to announce the first release of the IBEX Imaging Community knowledge-base!" > "$RELEASE_NOTES_FILE"
            echo "" >> "$RELEASE_NOTES_FILE"
          else
            create_draft_release_notes "$PREVIOUS_TAG" "${{ github.ref_name }}" "$RELEASE_NOTES_FILE"
          fi
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | # Using gh CLI to create a draft release
          gh release create ${{ github.ref_name }} \
            --draft \
            --title "${{ github.ref_name }}" \
            --notes-file "$RELEASE_NOTES_FILE"
